name: Deploy CDK to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Deploy CDK and capture output
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          OUTPUT_JSON=$(npx cdk deploy PostnordProjectServiceProviderEndStack --require-approval never --outputs-file -)
          OUTPUT_VALUE=$(echo $OUTPUT_JSON | jq -r '.vpcendpointservicename')
          echo "::set-output name=output_value::$OUTPUT_VALUE"

      - name: Use CDK Output
        run: |
          echo "CDK Output Value: ${{ steps.deploy.outputs.output_value }}"

      - name: Cleanup
        if: always()
        run: npx cdk destroy PostnordProjectServiceProviderEndStack --force