name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build --prefix Postnord-Service-Provider-Stack/

      - name: Deploy CDK Stack
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm install typescript
          npx tsc --project Postnord-Service-Provider-Stack/tsconfig.json
          npx cdk deploy --require-approval never --app "npx ts-node Postnord-Service-Provider-Stack/bin/postnord-project-service-provider-end.ts"
