name: test

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: cd Postnord-Service-Consumer-Stack && npm install

      - name: Install TypeScript
        run: cd Postnord-Service-Consumer-Stack && npm install -g typescript

      - name: Run test script
        run: cd Postnord-Service-Consumer-Stack && npm run test
